# Sample custom neural net architecture on iris data
### Oscar Scholin

In [2]:
# imports
import os # for paths
import pandas as pd # for managing the dataset
import numpy as np # for doing lin alg

# load in data
iris = pd.read_csv('/Users/oscarscholin/Downloads/iris_master.csv')
iris.head(10)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa

## Single hidden layer, batch of 1

In [28]:
# get single input vector corresponding to first row; output target is species one-hot encoded 
input = np.array(iris.iloc[:1, 1:-1])[0]
print(input)

# for output, we want a 3 dimenional vector with 1 in position of the species
species_list = list(iris['Species'].unique())
print(species_list)
species = str(np.array(iris.iloc[:1, -1:])[0][0])
print(species)

# now make one-hot encoded (i.e., 1 at class location and 0 everywhere else)
target = np.zeros(3, dtype=int)
index = species_list.index(species)
target[index]=1
print(target)


[5.1 3.5 1.4 0.2]
['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
Iris-setosa
[1 0 0]


In [23]:
# time for hidden layer!
# we want 5 neurons, so we will have a list of length 2 containins 4 values each for the weights
# and then a list with 2 elements for biases

# choose randomly: initialize weights!
weights = []
for i in range(2):
    neuron_list = []
    for i in range(4):
        neuron_list.append((np.random.random()-1)*0.5)
    weights.append(neuron_list)

# now for biases
biases=[]
for i in range(2):
    biases.append(((np.random.random())*5))

print(weights)
print('-------')
print(biases)
print('-------')

# now pass the data through the network
out = np.dot(weights, input) + biases
print(out)


[[-0.21729928455346753, -0.21061614923669658, -0.38160993315740144, -0.3429425729412465], [-0.3714523967572388, -0.13433413576363679, -0.12169803571866566, -0.13586201473866272]]
-------
[2.958427990142602, 4.328349364919774]
-------
[0.5102027  1.76622301]


In [24]:
# now need feed through another layer to be the outputs; has 3 layers bc 3 classes
# choose randomly: initialize weights!
weights = []
for i in range(3):
    neuron_list = []
    for i in range(len(out)):
        neuron_list.append((np.random.random()-1)*0.5)
    weights.append(neuron_list)

# now for biases
biases=[]
for i in range(3):
    biases.append(((np.random.random())*5))

print(weights)
print('-------')
print(biases)
print('-------')

# now pass the data through the network
out2 = np.dot(weights, out) + biases
print(out2)


[[-0.0004419357783263522, -0.3251432847256663], [-0.43533493671468854, -0.36614418564968776], [-0.19307994258740285, -0.24062956691162513]]
-------
[0.06328666462310006, 2.7401710584492553, 4.838861870678472]
-------
[-0.51121436  1.87136971  4.31534648]


In [27]:
# now need to pass through activation function to get values bn 0 and 1
# here use softmax
exp_vals = np.exp(out2 - np.max(out2)) #subtract max per row
probabilites = exp_vals / np.sum(exp_vals)
print(probabilites)
print('------')
print('chosen class:', species_list[np.argmax(probabilites)])

[0.0073199  0.07929542 0.91338468]
------
chosen class: Iris-virginica


In [30]:
# need to compute loss
# use categorical cross entropy loss
y_pred_clipped = np.clip(probabilites, 1e-7, 1-1e-7) #need to clip close to 0
correct_confidences = np.sum(y_pred_clipped*target)
negative_log_likelihoods = -np.log(correct_confidences)
print(negative_log_likelihoods)

4.917158995908196
